theme: jekyll-theme-cayman

title: Jinja2++

showcase: True

desc: >-
  j2 with variable precedence & more (Any Language)
  
images:
  - https://raw.githubusercontent.com/ms-jpq/jinja2pp/j2/screenshot/invert.png
